name: CI

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1','8.2']
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP with pecl and extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:v2
    - run: php --version
    
    # install
    - run: composer install --no-interaction --prefer-dist
    
    # script
    - run: vendor/bin/phpstan analyse -c phpstan.neon app
